/**
 * SafeSeed built-in schema presets. The four SafeSeed-native presets plus a
 * handful of practical ones that use the expanded catalog.
 */

export const PRESETS = [
  {
    id: "crm-contacts",
    label: "CRM Contacts",
    tagline: "IDs, obvious test names, reserved emails, NANPA fictitious phones.",
    origin: "SafeSeed native",
    schema: [
      { name: "account_id",  type: "opaqueId" },
      { name: "contact_id",  type: "opaqueId" },
      { name: "full_name",   type: "fullName" },
      { name: "email",       type: "email" },
      { name: "phone",       type: "phone" },
    ],
  },
  {
    id: "marketing-attribution",
    label: "Marketing Attribution",
    tagline: "Event, cookie, campaign IDs; constrained UTM landing URLs; hashed match keys.",
    origin: "SafeSeed native",
    schema: [
      { name: "event_id",      type: "opaqueId" },
      { name: "cookie_id",     type: "opaqueId" },
      { name: "campaign_id",   type: "opaqueId" },
      { name: "landing_url",   type: "marketingUrl" },
      { name: "email_sha256",  type: "sha256Email" },
      { name: "phone_sha256",  type: "sha256Phone" },
      { name: "timestamp",     type: "timestamp" },
    ],
  },
  {
    id: "hashed-audience",
    label: "Hashed Audience",
    tagline: "Audience + campaign IDs and catalog-derived SHA-256 match keys.",
    origin: "SafeSeed native",
    schema: [
      { name: "audience_id",   type: "opaqueId" },
      { name: "campaign_id",   type: "opaqueId" },
      { name: "email_sha256",  type: "sha256Email" },
      { name: "phone_sha256",  type: "sha256Phone" },
    ],
  },
  {
    id: "uk-contacts",
    label: "UK Contacts",
    tagline: "Lead/account IDs, obvious test name, reserved email, Ofcom drama mobile.",
    origin: "SafeSeed native",
    schema: [
      { name: "lead_id",     type: "opaqueId" },
      { name: "account_id",  type: "opaqueId" },
      { name: "full_name",   type: "fullName" },
      { name: "email",       type: "email" },
      { name: "mobile",      type: "ukPhone" },
      { name: "postcode",    type: "postalUkPostcode" },
    ],
  },
  // ---- practical extensions ----
  {
    id: "customer-roster",
    label: "Customer Roster",
    tagline: "Wide customer table with contact, demographic, and network fields.",
    origin: "Practical extension",
    schema: [
      { name: "id",          type: "opaqueId" },
      { name: "full_name",   type: "fullName" },
      { name: "email",       type: "email" },
      { name: "phone",       type: "phone" },
      { name: "dob",         type: "dob" },
      { name: "city",        type: "city" },
      { name: "country",     type: "country" },
      { name: "ip",          type: "ipv4" },
      { name: "created_at",  type: "timestamp" },
    ],
  },
  {
    id: "hr-employees",
    label: "HR Employees",
    tagline: "Employee record with professional and government-id fields.",
    origin: "Practical extension",
    schema: [
      { name: "employee_id", type: "opaqueId" },
      { name: "full_name",   type: "fullName" },
      { name: "email",       type: "email" },
      { name: "job_title",   type: "jobTitle" },
      { name: "department",  type: "department" },
      { name: "company",     type: "company" },
      { name: "hire_date",   type: "dateOnly" },
      { name: "ssn",         type: "ssn" },
      { name: "salary",      type: "randomInt", options: { min: 40000, max: 220000 } },
    ],
  },
  {
    id: "payments-log",
    label: "Payments Log",
    tagline: "Transaction log with designated-test PANs and IBANs.",
    origin: "Practical extension",
    schema: [
      { name: "txn_id",      type: "uuid" },
      { name: "customer_id", type: "opaqueId" },
      { name: "timestamp",   type: "timestamp" },
      { name: "amount",      type: "currencyAmount" },
      { name: "currency",    type: "currencyCode" },
      { name: "card_number", type: "creditCard" },
      { name: "iban",        type: "iban" },
      { name: "status",      type: "enum", options: { values: "authorized,captured,refunded,voided" } },
    ],
  },
  {
    id: "healthcare-visits",
    label: "Healthcare Visits",
    tagline: "Patient visits keyed to the NHS training number.",
    origin: "Practical extension",
    schema: [
      { name: "patient_id",  type: "opaqueId" },
      { name: "full_name",   type: "fullName" },
      { name: "dob",         type: "dob" },
      { name: "nhs",         type: "nhs" },
      { name: "visit_date",  type: "dateOnly" },
      { name: "provider",    type: "company" },
      { name: "language",    type: "language" },
    ],
  },
  {
    id: "iot-sensors",
    label: "IoT Sensor Log",
    tagline: "Device telemetry with locally-administered MAC and RFC-5737 IPs.",
    origin: "Practical extension",
    schema: [
      { name: "device_id",   type: "uuid" },
      { name: "mac",         type: "mac" },
      { name: "ip",          type: "ipv4" },
      { name: "timestamp",   type: "timestamp" },
      { name: "temperature", type: "randomFloat", options: { min: -20, max: 60 } },
      { name: "humidity",    type: "randomInt", options: { min: 0, max: 100 } },
      { name: "status",      type: "enum", options: { values: "ok,warn,error,offline" } },
    ],
  },
  {
    id: "api-usage",
    label: "API Usage Log",
    tagline: "Structured HTTP access log against fictitious endpoints.",
    origin: "Practical extension",
    schema: [
      { name: "request_id",  type: "uuid" },
      { name: "timestamp",   type: "timestamp" },
      { name: "method",      type: "httpMethod" },
      { name: "endpoint",    type: "endpoint" },
      { name: "ip",          type: "ipv4" },
      { name: "status_code", type: "httpStatus" },
      { name: "latency_ms",  type: "randomInt", options: { min: 5, max: 5000 } },
    ],
  },
];

export const PRESET_BY_ID = Object.fromEntries(PRESETS.map(p => [p.id, p]));
